/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mortgage;
import java.text.NumberFormat;
/**
 *
 * @author lyssa
 */
public class MFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form MortgageForm
     */
    public MFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calculateBtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        salaryField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        monthlyDebtField = new javax.swing.JTextField();
        maximumLoanField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        housePriceField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        interestRateBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        fsaMonthlyField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        convMonthlyField = new javax.swing.JTextField();
        calculateBtn2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        vaMonthlyField = new javax.swing.JTextField();
        usdaMonthlyField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        maximumMonthly = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        downPmtField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mortgage Calculator");
        setMinimumSize(new java.awt.Dimension(600, 520));
        setPreferredSize(new java.awt.Dimension(600, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        calculateBtn1.setText("Calculate");
        calculateBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(calculateBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        jLabel1.setText("Mortgage Calculator");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabel2.setText("First, let's determine how much you could qualify for.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 49, -1, -1));

        jLabel3.setText("Annual Income:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 69, -1, -1));
        getContentPane().add(salaryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 110, -1));

        jLabel4.setText("Monthly Debt:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));
        getContentPane().add(monthlyDebtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 96, -1));

        maximumLoanField.setEditable(false);
        maximumLoanField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        maximumLoanField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maximumLoanField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(maximumLoanField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 158, 30));

        jLabel5.setText("Maximum Monthly Payment (OAC):");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        jLabel6.setText("Now, let's determine your monthly payment.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 214, -1, -1));

        jLabel7.setText("House Asking Price:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 246, -1, -1));
        getContentPane().add(housePriceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 272, 110, -1));

        jLabel8.setText("Interest Rate:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 309, -1, -1));

        interestRateBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(interestRateBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 329, 54, -1));

        jLabel10.setText("Monthly Payments based on a 30 year term:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 246, -1, -1));

        fsaMonthlyField.setEditable(false);
        fsaMonthlyField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(fsaMonthlyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 158, 32));

        jLabel9.setText("FSA Loan:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        jLabel11.setText("VA Loan:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        convMonthlyField.setEditable(false);
        getContentPane().add(convMonthlyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 158, 32));

        calculateBtn2.setText("Calculate");
        calculateBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(calculateBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));

        jLabel12.setText("USDA Loan:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        vaMonthlyField.setEditable(false);
        getContentPane().add(vaMonthlyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 158, 32));

        usdaMonthlyField.setEditable(false);
        getContentPane().add(usdaMonthlyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 158, 32));

        jLabel13.setText("Standard Loan:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, -1));

        jLabel14.setText("Maximum Borrow Amount (OAC):");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        maximumMonthly.setEditable(false);
        maximumMonthly.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        maximumMonthly.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maximumMonthly.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(maximumMonthly, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 158, 30));

        jLabel15.setText("Down Payment:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));
        getContentPane().add(downPmtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBtn2ActionPerformed
       if(isValidData2())
       {
           double hp= Double.parseDouble(housePriceField.getText());
           double i= interestRateBox.getSelectedIndex()+4;
           double dp= Double.parseDouble(downPmtField.getText()); 
           double t=30;
           NumberFormat currency = NumberFormat.getCurrencyInstance();
           Insurance insurance=new Insurance(hp,dp);
           //Set FHA payment
           double fhaloan=(insurance.setUFMIP(0.0175));
           double fha=insurance.setFHA();
           Amortization loan=new Amortization(fhaloan,i,t);
           fsaMonthlyField.setText(currency.format(loan.getMonthlyPayment()));
           //Set VA payment
           double valoan=insurance.setUFMIP(0.0215);
           double va=insurance.setVA();
           loan=new Amortization(valoan,i,t);
           vaMonthlyField.setText(currency.format(loan.getMonthlyPayment()));
           //Set USDA payment
           double usdaloan=insurance.setUFMIP(0.01);
           double usda=insurance.setUSDA();
           loan=new Amortization(usdaloan,i,t);
           usdaMonthlyField.setText(currency.format(loan.getMonthlyPayment()));
           //Set Conventional payment
           double convLoan=hp;
           double conv=insurance.setConv();
           loan=new Amortization(convLoan,i,t);
           convMonthlyField.setText(currency.format(loan.getMonthlyPayment()));
         
       }
    }//GEN-LAST:event_calculateBtn2ActionPerformed

    private void calculateBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBtn1ActionPerformed
       if(isValidData())
       {
           Validator v = new Validator();
           double s =Double.parseDouble(salaryField.getText());
           double d =Double.parseDouble(monthlyDebtField.getText());
           Qualify qualify = new Qualify(s,d);
           
           NumberFormat currency = NumberFormat.getCurrencyInstance();
           if(qualify.getMax()>0)
           {
               maximumMonthly.setText(currency.format(qualify.getMax()));
               maximumLoanField.setText(currency.format(qualify.getMaxBorrow()));
           }
           else
           {
               v.isDebtFree(monthlyDebtField, "Monthly Debt");
           }  
       }    
    }//GEN-LAST:event_calculateBtn1ActionPerformed
    private boolean isValidData()
    {
        Validator v = new Validator();
        return
                v.isPresent(salaryField, "Annual Salary") &&
                v.isPresent(monthlyDebtField, "Monthly Debt") &&
                v.isDouble(salaryField, "Annual Salary") &&
                v.isDouble(monthlyDebtField, "Monthly Debt");
    }
    private boolean isValidData2()
    {
        Validator v = new Validator();
        return
                v.isPresent(housePriceField, "House Price") &&
                v.isPresent(downPmtField, "Down Payment") &&
                v.isDouble(housePriceField, "House Price") &&
                v.isDouble(downPmtField, "Down Payment");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MFrame1 frame=new MFrame1();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateBtn1;
    private javax.swing.JButton calculateBtn2;
    private javax.swing.JTextField convMonthlyField;
    private javax.swing.JTextField downPmtField;
    private javax.swing.JTextField fsaMonthlyField;
    private javax.swing.JTextField housePriceField;
    private javax.swing.JComboBox<String> interestRateBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField maximumLoanField;
    private javax.swing.JTextField maximumMonthly;
    private javax.swing.JTextField monthlyDebtField;
    private javax.swing.JTextField salaryField;
    private javax.swing.JTextField usdaMonthlyField;
    private javax.swing.JTextField vaMonthlyField;
    // End of variables declaration//GEN-END:variables
}
